import {test,after} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import * as f from './helpers/funding-fixture.mjs';import * as x from './helpers/funding-exact-cost-fixture.mjs';import {canonicalCostDecimal,createExactCostFixture,createExactCostService} from '../apps/api/src/funding/exactCostComponents.js';
const db=new PGlite();after(()=>db.close());await db.exec(f.fundingParentFixtureSQL);for(const m of ['fundingCoreMigration','fundingRlsMigration','fundingAuthMigration','fundingTemporalMigration','fundingCostsMigration','fundingReviewMigration'])await db.exec(await readFile(f[m],'utf8'));await db.exec(await readFile(x.exactCostMigration,'utf8'));
const q=(s,a=[])=>db.query(s,a);let tail=Promise.resolve(),before=false,afterCommit=false;
function database(role){return {async connect(){let release;const prior=tail;tail=new Promise(r=>release=r);await prior;await db.exec('SET ROLE '+role);return {async query(s,a){if(s==='COMMIT'&&before){before=false;throw Error('synthetic_commit_fault');}const r=await q(s,a);if(s==='COMMIT'&&afterCommit){afterCommit=false;throw Error('synthetic_commit_response_loss');}return r;},release(){db.exec('RESET ROLE').then(release);}};}};}
const fixture=createExactCostFixture(x.exactCostOptions),service=createExactCostService({ingestDatabase:database('funding_exact_cost_ingest'),calculatorDatabase:database('funding_exact_cost_calculator'),fixture,mode:'isolated'}),open=async key=>(await service.open(x.exactOperation(key))).operationId,receive=(op,key,value,delta)=>service.receive(x.exactCostOptions.secret,x.exactFact(op,key,value,delta));
test('exact decimal sums fractional minor units without floats, FX or financial changes',async()=>{const op=await open('fraction');await receive(op,'fraction_a');await receive(op,'fraction_b');const a=await service.inspect(op);assert.deepEqual(a.totals,[{currency:'USD',value:'0.01'}]);assert.equal(a.status,'provisional');await tail;assert.equal(Number((await q('SELECT count(*) n FROM funding_private.ledger_entries')).rows[0].n),0);});
test('latest source revision, not receipt order or sum of historical revisions, determines exact aggregate',async()=>{const op=await open('revision');await receive(op,'revision_a','0.007',{revision:2});await receive(op,'revision_a','0.005',{revision:1});await receive(op,'revision_b');assert.deepEqual((await service.inspect(op)).totals,[{currency:'USD',value:'0.012'}]);await tail;assert.equal(Number((await q('SELECT count(*) n FROM funding_exact_cost_private.component_revisions WHERE source_value IN ($1,$2)',['0.005','0.007'])).rows[0].n)>=3,true);});
test('twenty fee replays produce one component and operation-bound completeness is required',async()=>{const op=await open('fee');await receive(op,'fee_attempt');await Promise.all(Array.from({length:20},()=>receive(op,'fee_success','0.05',{kind:'verification_fee'})));assert.equal((await service.inspect(op)).components.length,2);const p=await x.completeness(service,fixture,op,'required');assert.equal((await service.attest(op,p)).status,'completed_fixture');assert.equal((await service.attest(op,p)).status,'duplicate');await assert.rejects(service.attest(await open('wrong_op'),p),/exact_completeness_proof_required/);});
test('same revision conflicts persist once and block completeness without overwriting original',async()=>{const op=await open('conflict');await receive(op,'clash');await Promise.all(Array.from({length:20},()=>receive(op,'clash','0.006')));assert.equal((await service.inspect(op)).status,'review');await assert.rejects(service.attest(op,await x.completeness(service,fixture,op)),/exact_incomplete/);await tail;assert.equal(Number((await q('SELECT count(*) n FROM funding_exact_cost_private.conflicts WHERE operation_id=$1',[op])).rows[0].n),1);});
test('missing/provisional price, fee basis and unassigned purpose cannot become final; currencies stay separate',async()=>{const op=await open('missing');await receive(op,'missing_value',null,{currency:null,qualification:'provisional'});await assert.rejects(service.attest(op,await x.completeness(service,fixture,op)),/exact_incomplete/);await receive(op,'missing_value','0.005',{revision:2});await assert.rejects(service.attest(op,await x.completeness(service,fixture,op,'required')),/exact_incomplete/);await receive(op,'euro_value','0.001',{currency:'EUR'});assert.deepEqual((await service.inspect(op)).totals,[{currency:'EUR',value:'0.001'},{currency:'USD',value:'0.005'}]);const id=(await service.open({...x.exactOperation('unknown'),eventRef:null,purpose:'unassigned'})).operationId;await receive(id,'unknown_value');await assert.rejects(service.attest(id,await x.completeness(service,fixture,id)),/exact_incomplete/);});
test('new revisions after completed fixture preserve immutable attestation and require review',async()=>{const op=await open('final');await receive(op,'final_price');const proof=await x.completeness(service,fixture,op);await service.attest(op,proof);await tail;const old=JSON.stringify((await q('SELECT * FROM funding_exact_cost_private.aggregate_attestations WHERE operation_id=$1',[op])).rows);await receive(op,'final_price','0.006',{revision:2});assert.equal((await service.inspect(op)).status,'review');assert.equal((await service.attest(op,proof)).status,'review');await tail;assert.equal(JSON.stringify((await q('SELECT * FROM funding_exact_cost_private.aggregate_attestations WHERE operation_id=$1',[op])).rows),old);});
test('commit faults never ACK; lost committed receipt retries once; deferred attestation failure rolls back',async()=>{const op=await open('commit');before=true;await assert.rejects(receive(op,'commit'),/exact_cost_unavailable/);afterCommit=true;await assert.rejects(receive(op,'commit'),/exact_cost_unavailable/);assert.equal((await receive(op,'commit')).outcome,'duplicate');const proof=await x.completeness(service,fixture,op);await tail;await db.exec("CREATE FUNCTION public.exact_commit_fault() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic_exact_commit_fault';END $$;CREATE CONSTRAINT TRIGGER exact_commit_fault AFTER INSERT ON funding_exact_cost_private.aggregate_attestations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.exact_commit_fault()");try{await assert.rejects(service.attest(op,proof),/exact_cost_unavailable/);await tail;assert.equal((await q('SELECT * FROM funding_exact_cost_private.aggregate_attestations WHERE operation_id=$1',[op])).rows.length,0);}finally{await db.exec('DROP TRIGGER exact_commit_fault ON funding_exact_cost_private.aggregate_attestations');}});
test('decimal grammar, privacy allowlist and trusted proof reject unsafe coercion and caller-final',async()=>{assert.equal(canonicalCostDecimal('0.0050'),'0.005');for(const v of [0.005,'NaN','-1','1e-3','00.5','0.0000000000001','1000000000000000000',' 1','Infinity'])assert.throws(()=>canonicalCostDecimal(v));const op=await open('privacy');for(const key of ['phone','phone_hash','device_id','nullifier','donorHMAC','adhesion_id','email','rawPayload','final','ownerApproved'])await assert.rejects(receive(op,'private','0.005',{[key]:'private'}),/invalid_exact_fact/);await assert.rejects(service.receive(x.exactCostOptions.ownerSecret,x.exactFact(op,'auth')),/exact_fixture_auth_required/);assert.throws(()=>createExactCostFixture({...x.exactCostOptions,mode:'production'}));assert.throws(()=>createExactCostFixture({...x.exactCostOptions,secret:x.exactCostOptions.proofSecret}));await assert.rejects(service.attest(op,true),/exact_completeness_proof_required/);});
test('roles have no financial permissions; facts immutable, invoker functions and cross-operation component scope',async()=>{const op=await open('roles');await receive(op,'scope');await assert.rejects(receive(await open('other_scope'),'scope'),/component_scope_conflict/);await tail;await assert.rejects(q('UPDATE funding_exact_cost_private.component_revisions SET source_revision=source_revision'),/append_only/);for(const role of ['funding_exact_cost_ingest','funding_exact_cost_calculator','anon','authenticated']){await db.exec('SET ROLE '+role);for(const sql of ['SELECT * FROM funding_private.annual_limits','SELECT * FROM funding_private.ledger_entries'])await assert.rejects(q(sql),e=>e.code==='42501');if(role.startsWith('funding_exact'))await assert.rejects(q('UPDATE public.protests SET hash_integridad=NULL'),e=>e.code==='42501');else await assert.rejects(q('SELECT * FROM funding_exact_cost_private.operations'),e=>e.code==='42501');await db.exec('RESET ROLE');}assert.equal(Number((await q("SELECT count(*) n FROM pg_proc WHERE pronamespace='funding_exact_cost_private'::regnamespace AND (prosecdef OR has_function_privilege('anon',oid,'EXECUTE') OR has_function_privilege('authenticated',oid,'EXECUTE'))")).rows[0].n),0);});

test('full decimal precision, explicit zero, stale completeness and incomplete manifest cannot fake a final aggregate',async()=>{
 const op=await open('precision');await receive(op,'large_a','999999999999999999.999999999999');await receive(op,'large_b','0.000000000001');await receive(op,'explicit_zero','0');assert.deepEqual((await service.inspect(op)).totals,[{currency:'USD',value:'1000000000000000000'}]);
 const stale=await x.completeness(service,fixture,op);await receive(op,'large_b','0.000000000002',{revision:2});await assert.rejects(service.attest(op,stale),/exact_stale_binding/);
 const omitted=await x.completeness(service,fixture,op,'not_applicable',{manifest:['synthetic_component_large_a']});await assert.rejects(service.attest(op,omitted),/exact_incomplete/);
});
