import Fastify from 'fastify';
import {test,after} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {randomUUID} from 'node:crypto';
import * as f from './helpers/funding-fixture.mjs';import * as s from './helpers/funding-sms-closure-fixture.mjs';import * as x from './helpers/funding-exact-cost-fixture.mjs';import * as i from './helpers/funding-sms-integration-fixture.mjs';
import {createBlockedTwilioAdapter} from '../apps/api/src/funding/blockedTwilioAdapter.js';import {createSmsIntegrationCandidate,createSmsIntegrationHandlers,registerSmsIntegrationCandidate} from '../apps/api/src/funding/smsIntegrationCandidate.js';
const db=new PGlite();after(()=>db.close());await db.exec(f.fundingParentFixtureSQL);for(const m of ['fundingCoreMigration','fundingRlsMigration','fundingAuthMigration','fundingTemporalMigration','fundingCostsMigration','fundingReviewMigration','fundingProviderMigration','fundingContinuityMigration','fundingRetentionMigration','fundingLifecycleMigration','fundingLifecycleReplayMigration'])await db.exec(await readFile(f[m],'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20261004183459_funding_owner_authority_contract.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20261004201818_funding_legacy_receipt_journal.sql',import.meta.url),'utf8'));for(const m of [s.smsClosureMigration,x.exactCostMigration,i.integrationMigration])await db.exec(await readFile(m,'utf8'));
const q=(sql,args=[])=>db.query(sql,args);let tail=Promise.resolve(),faultRole=null,afterCommit=false;
function database(role){return {async connect(){let release;const previous=tail;tail=new Promise(r=>release=r);await previous;await db.exec('SET ROLE '+role);return {async query(sql,args){if(sql==='COMMIT'&&faultRole===role&&!afterCommit){faultRole=null;throw Error('synthetic_commit_failure');}const r=await q(sql,args);if(sql==='COMMIT'&&faultRole===role&&afterCommit){faultRole=null;afterCommit=false;throw Error('synthetic_lost_commit_response');}return r;},release(){db.exec('RESET ROLE').then(release);}};}};}
const databases={bridgeDatabase:database('funding_sms_bridge'),executorDatabase:database('funding_sms_executor'),evidenceDatabase:database('funding_sms_evidence_ingest'),ingestDatabase:database('funding_exact_cost_ingest'),calculatorDatabase:database('funding_exact_cost_calculator')};
async function event(){await tail;return s.seedSmsEvent({query:q});}
async function evidenceState(){await tail;return {ledger:(await q('SELECT * FROM funding_private.ledger_entries ORDER BY transaction_id,account_id')).rows,quota:(await q('SELECT * FROM funding_private.annual_limits')).rows,finals:(await q('SELECT id,hash_integridad,saldo_euros FROM public.protests ORDER BY id')).rows};}
const open=async(build,key='x')=>{const e=await event();return {e,op:(await build.candidate.prepare(i.integrationInput(e,key))).operationId};};
test('integrated SDK intercepted transport, exact USD totals, missing fee and EUR hold without financial mutation',async()=>{
 const build=i.buildIntegration(databases),{op}=await open(build,'totals'),before=await evidenceState();assert.equal((await build.candidate.dispatch(op)).sent,true);const r=await build.candidate.collect(op);assert.deepEqual(r.cost.totals,[{currency:'USD',value:'0.01'}]);assert.equal(r.cost.components.length,3);assert.equal(r.cost.status,'pending_evidence');assert.equal(r.feeBasis,'unknown');assert.equal(r.settlementBlocked,true);assert.deepEqual(await evidenceState(),before);assert.ok(!JSON.stringify(r).includes('+34999999999'));assert.ok(!JSON.stringify(r).includes('VE'));assert.ok(!JSON.stringify(r).includes('VL'));await tail;assert.equal(Number((await q("SELECT count(*) n FROM funding_private.cost_reservations WHERE state='reserved'")).rows[0].n)>0,true);
});
test('twenty prepares/dispatches/collections compose once and do not multiply cost components',async()=>{
 const b=i.buildIntegration(databases),e=await event(),input=i.integrationInput(e,'retries');const prepared=await Promise.all(Array.from({length:20},()=>b.candidate.prepare(input)));assert.equal(new Set(prepared.map(x=>x.operationId)).size,1);const op=prepared[0].operationId;const results=await Promise.all(Array.from({length:20},()=>b.candidate.dispatch(op)));assert.equal(results.filter(x=>x.sent).length,1);assert.equal(Object.values(b.adapter.counts()).reduce((a,c)=>a+c,0),1);await Promise.all(Array.from({length:20},()=>b.candidate.collect(op)));assert.equal((await b.candidate.inspect(op)).cost.components.length,3);
});
test('lost provider response and recomposition never resend and no absent lookup is interpreted as free',async()=>{
 const b=i.buildIntegration(databases,{fault:'timeout'}),{op}=await open(b,'unknown');assert.equal((await b.candidate.dispatch(op)).dispatchState,undefined);assert.equal((await b.candidate.inspect(op)).dispatchState,'unknown');const next=i.buildIntegration(databases);assert.equal((await next.candidate.dispatch(op)).claimed,false);assert.deepEqual(next.adapter.counts(),{});await assert.rejects(next.candidate.collect(op),e=>e.code==='provider_evidence_unavailable'&&!e.message.includes('+349'));assert.equal((await next.candidate.inspect(op)).settlementBlocked,true);
});
test('unordered changed provider prices preserve original and force review instead of promoting a newer timestamp',async()=>{
 let value='0.005';const b=i.buildIntegration(databases,{respond:async r=>i.sdkResponder({prices:[value]})(r)}),{op}=await open(b,'revision');await b.candidate.dispatch(op);await b.candidate.collect(op);value='0.007';const next=await b.candidate.collect(op);assert.equal(next.cost.status,'review');assert.deepEqual(next.cost.totals,[{currency:'USD',value:'0.005'}]);await tail;assert.equal(Number((await q('SELECT count(*) n FROM funding_exact_cost_private.conflicts')).rows[0].n)>0,true);
});
test('provider price syntax, wrong ownership, pagination redirect and bound reject raw unsafe responses',async()=>{
 for(const [key,options] of [['number',{prices:[0.005]}],['currency',{rawDelta:{price:{value:'0.005',currency:'usd'}}}],['owner',{rawDelta:{verification_sid:'VE'+'f'.repeat(32)}}],['redirect',{next:'https://evil.invalid/v2/Attempts'}],['pages',{next:'https://verify.twilio.com/v2/Attempts?PageToken=loop'}]]){const b=i.buildIntegration(databases,options),{op}=await open(b,key);await b.candidate.dispatch(op);await assert.rejects(b.candidate.collect(op),e=>e.code==='provider_evidence_unavailable');}
});
test('bridge commit failure and lost claim commit never allow a send before durable binding and claim',async()=>{
 const b=i.buildIntegration(databases),e=await event(),input=i.integrationInput(e,'fault');faultRole='funding_sms_bridge';await assert.rejects(b.candidate.prepare(input),/integration_binding_unavailable/);assert.deepEqual(b.adapter.counts(),{});const op=(await b.candidate.prepare(input)).operationId;faultRole='funding_sms_executor';afterCommit=true;await assert.rejects(b.candidate.dispatch(op),/sms_rehearsal_unavailable/);assert.equal((await b.candidate.dispatch(op)).claimed,false);assert.deepEqual(b.adapter.counts(),{});assert.equal((await b.candidate.inspect(op)).settlementBlocked,true);
});
test('close prevents new dispatch, late collection preserves facts and settlement is explicitly blocked',async()=>{
 const b=i.buildIntegration(databases),{e,op}=await open(b,'closed');await b.candidate.dispatch(op);const before=await evidenceState();await assert.rejects(b.candidate.close(e),/event_not_ended/);await tail;await q("UPDATE public.protests SET ends_at=clock_timestamp()-interval '1 second' WHERE id=$1",[e]);await b.candidate.close(e);await b.candidate.collect(op);assert.deepEqual(await evidenceState(),before);await assert.rejects(b.candidate.close(e,true),/integration_settlement_blocked/);const c=i.buildIntegration(databases),next=await open(c,'closed_before');await tail;await q("UPDATE public.protests SET ends_at=clock_timestamp()-interval '1 second' WHERE id=$1",[next.e]);await c.candidate.close(next.e);await assert.rejects(c.candidate.dispatch(next.op),/sms_dispatch_closed/);assert.deepEqual(c.adapter.counts(),{});
});
test('private handler candidate preserves default legacy and requires participation-owned authorization, ignores sms_sent for cost',async()=>{
 const legacy={requestOtp:async()=>({legacy:true}),verifyOtp:async()=>({legacy:true}),join:async()=>({legacy:true})};assert.deepEqual(await createSmsIntegrationHandlers({legacy}).requestOtp({phone:'ordinary'}),{legacy:true});const b=i.buildIntegration(databases),e=await event(),tokens=new Map();let admitted=0,joined=0;
 const participation={async admit(id){assert.equal(id,e);admitted++;},async issue(id){const token=randomUUID();tokens.set(token,id);return token;},async join(input){assert.equal(tokens.get(input.participationToken),input.eventId);assert.ok(!('sms_sent' in input));joined++;return {joined:true};}};
 const h=createSmsIntegrationHandlers({enabled:true,candidate:b.candidate,participation});await assert.rejects(h.requestOtp({...i.integrationInput(e,'generic'),destination:'+15005550006',purpose:'generic'}),/unsupported_otp_purpose/);assert.equal(admitted,0);const r=await h.requestOtp({...i.integrationInput(e,'handlers'),destination:'+15005550006',purpose:'event_sms'});const v=await h.verifyOtp({operationId:r.operationId,code:'000000'});assert.equal(v.approved,true);const before=await evidenceState();await assert.rejects(h.join({eventId:e,method:'phone_otp',participationToken:'forged'}));assert.deepEqual(await h.join({eventId:e,method:'phone_otp',participationToken:v.participationToken,sms_sent:true}),{joined:true});assert.equal(joined,1);assert.deepEqual(await evidenceState(),before);await assert.rejects(h.join({eventId:e,method:'institutional_email_otp'}),/participation_policy_pending/);
});
test('immutable scope binding, restricted bridge actor, no real credentials or production transport',async()=>{
 const b=i.buildIntegration(databases),{op}=await open(b,'roles');await tail;await assert.rejects(q('UPDATE funding_sms_bridge_private.bindings SET event_id=event_id'),/append_only/);for(const role of ['funding_sms_bridge','anon','authenticated']){await db.exec('SET ROLE '+role);for(const sql of ['SELECT * FROM funding_private.annual_limits','SELECT * FROM funding_private.ledger_entries'])await assert.rejects(q(sql),e=>e.code==='42501');if(role==='funding_sms_bridge')await assert.rejects(q('UPDATE public.protests SET hash_integridad=NULL'),e=>e.code==='42501');else await assert.rejects(q('SELECT * FROM funding_sms_bridge_private.bindings'),e=>e.code==='42501');await db.exec('RESET ROLE');}await tail;const existing=(await q('SELECT * FROM funding_sms_bridge_private.bindings WHERE sms_operation_id=$1',[op])).rows[0];await db.exec('SET ROLE funding_sms_bridge');await assert.rejects(q('SELECT funding_sms_bridge_private.bind($1,$2,$3)',[op,existing.exact_operation_id,randomUUID()]),/bridge_binding_conflict/);await db.exec('RESET ROLE');assert.throws(()=>createBlockedTwilioAdapter({mode:'production',respond:i.sdkResponder(),referenceSecret:i.referenceSecret}));assert.throws(()=>createSmsIntegrationCandidate({mode:'isolated',adapter:{kind:'blocked_twilio_sdk'}}));
});

test('disposable Fastify routes are absent by default; active harness enforces gates and sanitizes injected errors',async()=>{
 const off=Fastify();await off.register(registerSmsIntegrationCandidate);assert.equal((await off.inject({method:'POST',url:'/request-otp',payload:{}})).statusCode,404);await off.close();
 const b=i.buildIntegration(databases),e=await event(),on=Fastify();let token=null;const participation={async admit(id){assert.equal(id,e);},async issue(){token=randomUUID();return token;},async join(input){if(input.participationToken!==token)throw Error('private phone +34999999999');return {joined:true};}};
 await on.register(registerSmsIntegrationCandidate,{enabled:true,candidate:b.candidate,participation});
 try{const input={...i.integrationInput(e,'http'),purpose:'event_sms',destination:'+15005550006'};const denied=await on.inject({method:'POST',url:'/request-otp',payload:{...input,purpose:'generic'}});assert.equal(denied.statusCode,409);assert.deepEqual(b.adapter.counts(),{});
 const r=await on.inject({method:'POST',url:'/request-otp',payload:input});assert.equal(r.statusCode,200);assert.equal(r.json().sent,true);const verified=await on.inject({method:'POST',url:'/verify-otp',payload:{operationId:r.json().operationId,code:'000000'}});assert.equal(verified.json().participationToken,token);
 const forged=await on.inject({method:'POST',url:'/join',payload:{eventId:e,method:'phone_otp',participationToken:'forged',sms_sent:true}});assert.equal(forged.statusCode,503);assert.ok(!forged.body.includes('+349'));const joined=await on.inject({method:'POST',url:'/join',payload:{eventId:e,method:'phone_otp',participationToken:token,sms_sent:false}});assert.equal(joined.statusCode,200);assert.equal(joined.json().joined,true);
 }finally{await on.close();}
});
