// evidentialScope.js
// ---------------------------------------------------------------------------
// Deterministic "Statement of Evidential Scope" for a Voice Protest report.
//
// Produces, for any convocatoria, three fixed sections:
//   1. demonstrates          — what the report DOES establish (affirmative, leads)
//   2. outside_scope          — outside the report's scope (kept short: affiliation, truth, representativeness)
//   3. methods               — the verification methods actually used
// plus:
//   participation_rate       — ONLY when the system owns the universe (census). Never estimated.
//   admission_rules          — the public rules the convocatoria passed to be admitted.
//
// Design constraints (from the audit conversation):
//   - Autogenerated and DETERMINISTIC. Never author-written. It is a function of
//     the data (scope, dominio_email, requiere_censo, local_verified), exactly as
//     auditable as the integrity hash.
//   - "Evidence quality, not legitimacy": describes the strength of available
//     verification SIGNALS, never a hierarchy of participants.
//   - Affirmative first; the "outside scope" list is deliberately short.
//   - Output is i18n keys + params. The frontend renders them in NEUTRAL
//     typography — no checks/crosses, stars, or colour grading (those re-create a
//     pass/fail hierarchy). Icons are a rendering choice the report must avoid.
//
// Returns plain data; the caller adds it to the /informe response as
// `evidential_scope` and the report renders it via i18n.
// ---------------------------------------------------------------------------

/** Resolve the verification mode from the protest row. */
function modeOf(protest) {
  if (protest.dominio_email) {
    return protest.requiere_censo ? 'institutional_census' : 'institutional_email';
  }
  // geographic scopes
  return protest.scope; // 'national' | 'regional' | 'local' | 'global'
}

/**
 * @param {object} protest  full protests row (scope, dominio_email, requiere_censo,
 *                          country_name, convocatoria_osm_id, convocatoria_ciudad_nombre,
 *                          target_wikidata_id, tipo_abuso, fuente_url ...)
 * @param {object} agg      aggregates already computed by /informe:
 *                          { total, desglose_geografico_local, paises_distintos,
 *                            census_eligible? }
 * @returns {object} evidential_scope
 */
export function buildEvidentialScope(protest, agg = {}) {
  const mode = modeOf(protest);
  const total = agg.total ?? protest.count ?? 0;
  const dgl = agg.desglose_geografico_local || null;
  const localVerified = dgl?.local_verified?.count ?? 0;
  const territory = protest.convocatoria_ciudad_nombre || protest.country_name || null;

  const demonstrates = [];
  const outside_scope = [];   // framed as methodological delimitation, not a deficiency
  const methods = [];

  // ── "unique participation" line (identifier-specific key for clean i18n) ──
  demonstrates.push({
    key: protest.dominio_email
      ? 'demonstrates.unique_participation_email'
      : 'demonstrates.unique_participation_phone',
    params: {},
  });

  // ── mode-specific demonstrable + affiliation caveat + methods ────────────
  switch (mode) {
    case 'national':
      demonstrates.push({ key: 'demonstrates.sim_country', params: { country: protest.country_name } });
      outside_scope.push({ key: 'not.affiliation_geographic', params: {} });
      methods.push({ key: 'methods.sms_otp' });
      methods.push({ key: 'methods.sim_country' });
      methods.push({ key: 'methods.ip' });
      break;

    case 'regional':
      // Honesty: regional is a creator DECLARATION, not a technical restriction —
      // unless an OSM entity + GPS verified some adhesions territorially.
      demonstrates.push({ key: 'demonstrates.sim_country', params: { country: protest.country_name } });
      if (dgl && localVerified > 0) {
        demonstrates.push({ key: 'demonstrates.local_verified_region', params: { count: localVerified, total, territory } });
        methods.push({ key: 'methods.gps_osm_region', params: { territory } });
      }
      outside_scope.push({ key: 'not.region_presence', params: { territory } });
      methods.unshift({ key: 'methods.sms_otp' });
      methods.push({ key: 'methods.sim_country' });
      methods.push({ key: 'methods.ip' });
      break;

    case 'local':
      if (dgl && localVerified > 0) {
        demonstrates.push({ key: 'demonstrates.local_verified_municipality', params: { count: localVerified, total, territory } });
        methods.push({ key: 'methods.gps_osm_municipality', params: { territory } });
      }
      outside_scope.push({ key: 'not.residence', params: { territory } });
      methods.unshift({ key: 'methods.sms_otp' });
      methods.push({ key: 'methods.ip' });
      break;

    case 'global':
      demonstrates.push({ key: 'demonstrates.country_breakdown', params: {} });
      outside_scope.push({ key: 'not.affiliation_geographic', params: {} });
      methods.push({ key: 'methods.sms_otp' });
      methods.push({ key: 'methods.ip' });
      break;

    case 'institutional_email':
      demonstrates.push({ key: 'demonstrates.institutional_affiliation', params: { domain: protest.dominio_email } });
      outside_scope.push({ key: 'not.institutional_role', params: {} });
      methods.push({ key: 'methods.email_otp', params: { domain: protest.dominio_email } });
      break;

    case 'institutional_census':
      demonstrates.push({ key: 'demonstrates.institutional_affiliation', params: { domain: protest.dominio_email } });
      demonstrates.push({ key: 'demonstrates.census_vouching', params: {} });
      outside_scope.push({ key: 'not.institutional_role', params: {} });
      methods.push({ key: 'methods.email_otp', params: { domain: protest.dominio_email } });
      methods.push({ key: 'methods.census_vouching' });
      break;
  }

  // ── core "outside scope" lines, always present (kept short) ──────────────
  outside_scope.push({ key: 'not.truth', params: {} });
  outside_scope.push({ key: 'not.representative', params: {} });

  // ── public auditability is always demonstrable ───────────────────────────
  demonstrates.push({ key: 'demonstrates.public_auditability', params: {} });

  // ── participation rate: ONLY when the universe is owned by the system ─────
  // Census defines a registered member set. Email-domain mode does NOT (the
  // platform cannot know how many @domain addresses exist). Never estimate.
  let participation_rate = null;
  if (mode === 'institutional_census' && Number.isInteger(agg.census_eligible) && agg.census_eligible > 0) {
    participation_rate = {
      eligible: agg.census_eligible,
      count: total,
      rate: Math.round((total / agg.census_eligible) * 1000) / 10, // one decimal, %
      source: 'registered_census',
    };
  }

  // ── admission rules applied (the public rules the convocatoria passed) ────
  const admission_rules = [];
  if (protest.target_wikidata_id) {
    admission_rules.push({ key: 'admission.public_institution', params: { wikidata: protest.target_wikidata_id } });
  }
  if (protest.tipo_abuso) {
    admission_rules.push({ key: 'admission.abuse_category', params: { category: protest.tipo_abuso } });
  }
  admission_rules.push({ key: 'admission.source_accepted', params: {} });
  admission_rules.push({ key: 'admission.petition_filter', params: {} });
  if (protest.target_wikidata_id) {
    admission_rules.push({ key: 'admission.wikidata_verified', params: {} });
  }

  return {
    mode,
    demonstrates,
    outside_scope,
    methods,
    participation_rate,
    admission_rules,
    // schema marker so the frontend/consumers know the contract version
    version: 1,
  };
}

// ---------------------------------------------------------------------------
// Canonical English text for each key. This is the reference copy; the
// production app keeps these under locales/{es,en,fr,zh}.json (the function
// above only chooses WHICH keys appear). Rendered in neutral typography.
// ---------------------------------------------------------------------------
export const EVIDENTIAL_SCOPE_EN = {
  'demonstrates.unique_participation_phone': () =>
    `Unique, verified participation: each adhesion comes from a distinct verified phone number, counted once per convocatoria.`,
  'demonstrates.unique_participation_email': () =>
    `Unique, verified participation: each adhesion comes from a distinct verified institutional email address, counted once per convocatoria.`,
  'demonstrates.sim_country': (p) =>
    `Each participant holds a SIM registered in ${p.country}.`,
  'demonstrates.country_breakdown': () =>
    `The country of each participant is recorded and shown in the geographic breakdown.`,
  'demonstrates.local_verified_municipality': (p) =>
    `${p.count} of ${p.total} adhesions were geographically verified: GPS placed the participant inside the declared municipality${p.territory ? ` (${p.territory})` : ''}, matched against its OpenStreetMap entity.`,
  'demonstrates.local_verified_region': (p) =>
    `${p.count} of ${p.total} adhesions were geographically verified: GPS placed the participant inside the declared region${p.territory ? ` (${p.territory})` : ''}, matched against its OpenStreetMap entity.`,
  'demonstrates.institutional_affiliation': (p) =>
    `Each participant holds a verified email address in the institutional domain ${p.domain}, evidencing affiliation with that institution.`,
  'demonstrates.census_vouching': () =>
    `Affiliation is additionally supported by peer vouching within the institutional census.`,
  'demonstrates.public_auditability': () =>
    `The result is publicly auditable: the closed report carries an integrity hash and per-adhesion public commitments that anyone can verify independently.`,

  'not.affiliation_geographic': () =>
    `That participants belong to any specific affected community: no territorial or institutional membership was verified.`,
  'not.region_presence': (p) =>
    `That participants are physically in ${p.territory || 'the declared region'}: regional scope is a declaration by the creator, and participants are verified as national, not as present in the region.`,
  'not.residence': (p) =>
    `That participants are legally resident in ${p.territory || 'the municipality'}: GPS is a verification signal, not proof of residence, and can be spoofed.`,
  'not.institutional_role': () =>
    `The participant's role or status within the institution (for example active student versus staff), nor that the whole institution is represented.`,
  'not.truth': () =>
    `That the reported facts are true: Voice Protest records verified participation, not the validity of the claim.`,
  'not.representative': () =>
    `That the result represents the entire affected population: it measures those who chose to participate.`,

  'methods.sms_otp': () => `SMS one-time-password verification of a real phone number (Twilio Verify).`,
  'methods.email_otp': (p) => `Institutional email one-time-password verification (domain ${p.domain}).`,
  'methods.census_vouching': () => `Peer vouching within the institutional census.`,
  'methods.sim_country': () => `SIM country-of-registration signal.`,
  'methods.gps_osm_municipality': (p) => `GPS reverse-geocoded against the OpenStreetMap entity of the declared municipality${p.territory ? ` (${p.territory})` : ''}.`,
  'methods.gps_osm_region': (p) => `GPS reverse-geocoded against the OpenStreetMap entity of the declared region${p.territory ? ` (${p.territory})` : ''}.`,
  'methods.ip': () => `Approximate IP geolocation, used as a secondary signal (not stored in plain text).`,

  'admission.public_institution': (p) => `Recipient is a public institution, verified on Wikidata (${p.wikidata}).`,
  'admission.abuse_category': (p) => `A specific public-abuse category was declared: ${p.category}.`,
  'admission.source_accepted': () => `A documentary source was provided and accepted.`,
  'admission.petition_filter': () => `The source passed the petition-platform filter (change.org, avaaz.org, etc. are rejected).`,
  'admission.wikidata_verified': () => `Recipient validation was performed server-side via the Wikidata API.`,
};

/** Render a scope object to plain English lines (reference / testing helper). */
export function renderStatementEn(scope) {
  const line = (item) => {
    const fn = EVIDENTIAL_SCOPE_EN[item.key];
    return fn ? fn(item.params || {}) : `[${item.key}]`;
  };
  return {
    'What this report demonstrates': scope.demonstrates.map(line),
    'Outside the scope of this report': scope.outside_scope.map(line),
    'Verification methods used': scope.methods.map(line),
    'Participation rate': scope.participation_rate
      ? [`${scope.participation_rate.count} of ${scope.participation_rate.eligible} registered (${scope.participation_rate.rate}%).`]
      : ['(not shown — no system-owned universe)'],
    'Admission rules applied': scope.admission_rules.map(line),
  };
}
